### ISSUE TITLE
Text labels for dataset UI widgets (e.g, checkbox widget "Load FAKE1001 dataset" + file import widget)

### ISSUE THREAD

**Issue by mbaljko** [LePa-YU/Visualizer#11]
Hi Elmira, could we tweak the text labels to be: 
1. for the checkbox widget, label should be "Load FAKE1001 dataset or Load other dataset (default)" instead of "Load FAKE1001 dataset"
2. for the file import widget, can the label be "Load dataset, Drag and drop file here" instead of "Drag and drop file here"?
3. if yes for 2, then pls  remove the "Enter your csv file" label, it becomes redundant

keep up the awesome work!!!!

**Comment by ElmiraOn** [comment]
something like this?
![image](https://user-images.githubusercontent.com/90576588/206324062-a4f72ccb-b879-407c-8d3e-29def73030ad.png)

**Comment by mbaljko** [comment]
yes, looks good, thx
