### ISSUE TITLE
Atomic ER tooltip

### ISSUE THREAD

**Issue by ElmiraOn** [LePa-YU/Visualizer#16]
as previous discussion new elements are added to the atomic ERs tooltip to give more info to the user:

Atomic ERs contained in iER:
![LePa Visualizer — Mozilla Firefox 2023-02-03 10_08_55 AM (2)](https://user-images.githubusercontent.com/90576588/216638020-0b584a61-daa4-4ed8-a60c-4f87980a3e80.png)

Atomic ERs contained in aER:
![LePa Visualizer — Mozilla Firefox 2023-02-03 10_10_59 AM (2)](https://user-images.githubusercontent.com/90576588/216638367-526df407-ffa4-4b57-b400-71a335eaa7ce.png)

Atomic ERs contained in rER:

![LePa Visualizer — Mozilla Firefox 2023-02-03 10_12_28 AM (2)](https://user-images.githubusercontent.com/90576588/216638644-469273fc-1845-4ea6-b7b0-d16275f645f4.png)

**Comment by biltzerpos** [comment]
Great, we'll discuss today. Two typos: Avaiable and Rubic.
