### ISSUE TITLE
Clicking "Add Relation" button twice creates new path

### ISSUE THREAD

**Issue by NiharikaRajnish** [LePa-YU/Visualizer#25]
If "Add Relation" Button is clicked twice, a new path appears that is not attached to the end node.
Steps to recreate: 
1. Create a new ER
2. Add a comes after relation from Start to the new ER
<img width="585" alt="Screen Shot 2023-10-11 at 2 17 20 PM" src="https://github.com/LePa-YU/Visualizer/assets/74378254/7766db22-ceef-47fe-8163-ab13ced6a2b5">

3. Click Add Relation Button again 

<img width="566" alt="Screen Shot 2023-10-11 at 2 17 26 PM" src="https://github.com/LePa-YU/Visualizer/assets/74378254/ad4e1b03-03b6-4650-aae2-c8d95fb938ee">

**Comment by ElmiraOn** [comment]
Fixed the bug with check for existence of relationship
