### ISSUE TITLE
Color Palette feedback 

### ISSUE THREAD

**Issue by ElmiraOn** [LePa-YU/Visualizer#6]
Hello everyone!

I changed the colour palette of the visualizer to pink, orange, tan, and green where:

1. pink represents aER + rER and their assess relationship
2. orange represents iER
3. tan  represents any node that is not specified as aER, rER, iER and has isPartOf relationship with any of the nodes (the relation is also of the same colour)
4. green represents the required relationship between aER and iER

If you have any thoughts on how to improve this visualization please let me know :)

**Comment by ElmiraOn** [comment]
I also added a small colour picker, set initially on the colours above which you can use to experiment with different colours

**Comment by mbaljko** [comment]
looks great!!! we can close this now
