### ISSUE TITLE
Rename the three available views

### ISSUE THREAD

**Issue by biltzerpos** [LePa-YU/Visualizer#7]
The three views in the drop down menu should be renamed as:

- View 1: All ERs
- View 2: Course Overview
- View 3: Summative assessment only

  The third view needs to be implemented. It contains only aERs and rERs.

**Comment by ElmiraOn** [comment]
done :) 

to make the third view I had to add comesAfter_aER relationship to show relationships between aER

**Comment by biltzerpos** [comment]
Great, three small changes:
1. Swap the first and last view in the list, i.e. Summative assessment should be first, course overview next, and then all ERs.
2. Add the actual words "View 1", View 2" etc. at the beginning of each item
3. Instead of calling this element Options, and then "select graph", just have a title that says "Select view"

**Comment by ElmiraOn** [comment]
Just to be sure? the graph options from top to bottom would be:

1. View 1: Summative assessment only
2. View 2: Course Overview
3. View 3: All ERs



> 
>     2. Add the actual words "View 1", View 2" etc. at the beginning of each item
>

**Comment by biltzerpos** [comment]
Correct.
