### ISSUE TITLE
Polishing the demo dataset

### ISSUE THREAD

**Issue by biltzerpos** [LePa-YU/Visualizer#8]
We should refer to the demo dataset, as the dataset for course FAKE1001. The UI should then say: "Load FAKE1001 dataset".
Also, replace all references to Week with Module, e.g. instead of "Week 1: Lecture Video", it should be "Module 1: Lecture Video".

**Comment by ElmiraOn** [comment]
done :)
The demo data is now FAKE1001.csv under the Data folder and is used for the demo selection in visualizer

**Comment by biltzerpos** [comment]
Great, can we add a link that says "Other datasets" next to the checkbox for FAKE1001? It should link to https://github.com/LePa-YU/Datasets

**Comment by ElmiraOn** [comment]
added :D, Just a precondition: all the datasets that are to be used must have the same columns as the one in the demo otherwise the system will not perform as expected
